import fc from 'fast-check';
import { plainToInstance } from 'class-transformer';
import { validate } from 'class-validator';

import { RegisterDto } from '../dto/register.dto';

// ---------------------------------------------------------------------------
// Property-based tests for email validation on RegisterDto.
//
// Property 1: Email validation accepts valid emails and rejects invalid ones.
// Validates: Requirements 1.1, 1.2
//
// The RegisterDto uses @IsEmail() on the `email` field. When validation of an
// email fails, class-validator attaches an `isEmail` key to the field's
// `constraints` object. We build each DTO with a known-valid password so that
// only the email field is under test.
// ---------------------------------------------------------------------------

const VALID_PASSWORD = 'StrongPass1!';

/**
 * Validate a RegisterDto built from the given email (plus a valid password)
 * and return the `isEmail` constraint error for the email field, if any.
 */
async function getEmailError(email: unknown): Promise<string | undefined> {
  const dto = plainToInstance(RegisterDto, { email, password: VALID_PASSWORD });
  const errors = await validate(dto);
  const emailError = errors.find((e) => e.property === 'email');
  return emailError?.constraints?.isEmail;
}

describe('RegisterDto email validation — property tests (Requirements 1.1, 1.2)', () => {
  // -------------------------------------------------------------------------
  // Sub-property 1: any valid email produces NO isEmail error.
  // -------------------------------------------------------------------------
  it('accepts any valid email generated by fc.emailAddress() (no isEmail error)', async () => {
    await fc.assert(
      fc.asyncProperty(fc.emailAddress(), async (email) => {
        const isEmailError = await getEmailError(email);
        expect(isEmailError).toBeUndefined();
      }),
      { numRuns: 200 },
    );
  });

  // -------------------------------------------------------------------------
  // Sub-property 2: strings that are clearly not emails produce an isEmail
  // error. We use an arbitrary that intentionally omits a well-formed
  // local@domain.tld shape, filtered to guarantee it is genuinely invalid.
  // -------------------------------------------------------------------------
  it('rejects arbitrary non-email strings (isEmail error present)', async () => {
    // A loose structural check mirroring a well-formed address. We only use it
    // to EXCLUDE anything that might accidentally be a valid email, keeping the
    // arbitrary firmly in the invalid space. We do NOT use it as the assertion.
    const looksLikeEmail = (s: string): boolean =>
      /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);

    const invalidEmail = fc
      .oneof(
        // Arbitrary strings with no '@' at all.
        fc.string().filter((s) => !s.includes('@')),
        // Common malformed shapes.
        fc.constantFrom(
          'notanemail',
          'foo@',
          '@bar.com',
          'foo@bar',
          'foo bar@baz.com',
          'foo@@bar.com',
          'foo@bar..com',
          'plainaddress',
          '@',
          'a@b@c.com',
          '',
        ),
      )
      // Guarantee the generated value is genuinely not a valid email.
      .filter((s) => !looksLikeEmail(s));

    await fc.assert(
      fc.asyncProperty(invalidEmail, async (email) => {
        const isEmailError = await getEmailError(email);
        expect(isEmailError).toBeDefined();
      }),
      { numRuns: 200 },
    );
  });

  // -------------------------------------------------------------------------
  // Example-based sanity checks that complement the properties above.
  // -------------------------------------------------------------------------
  it('accepts a representative valid email', async () => {
    expect(await getEmailError('user.name@example.com')).toBeUndefined();
  });

  it('rejects a representative invalid email', async () => {
    expect(await getEmailError('not-an-email')).toBeDefined();
  });
});
